Python 2.7:
  script:
  - py_version=2.7
  - EXTRA_INSTALL=numpy
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  except:
  - tags

Python 3:
  script:
  - py_version=3
  - EXTRA_INSTALL=numpy
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  except:
  - tags
